## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  - windows
  
julia:
  - 1.4.1
  - nightly

allow_failures:
  - julia: 1.4.1
  - julia: nightly

notifications:
  email: false

git:
  depth: false

script:
  - export JULIA_PROJECT=""
  - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true);'

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder()); Coveralls.submit(process_folder())'



